version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - test

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    depends_on:
      - rabbitmq
    environment:
      - STREAMLIT_SERVER_ENABLE_WEBSOCKET_COMPRESSION=false
      - STREAMLIT_SERVER_PORT=8501
    command: streamlit run ui/dashboard.py
    networks:
      - test

networks:
  test:
